version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - '15432:5432'
    networks:
      - hex-network
    hostname: db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '15433:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - hex-network

  hex-nest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hex-nest
    env_file:
      - .env
    ports:
      - '15434:5434'
    depends_on:
      - db
    networks:
      - hex-network

volumes:
  pg-data:
  pgadmin-data:

networks:
  hex-network:
